#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

console_title_template = '{{.PWD}}{{if .Root}} : root{{end}} : {{.Shell}}'
final_space = true
version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '╭─'
    foreground = 'white'
    background = 'transparent'

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = 'black'
    background = 'white'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

    [blocks.segments.properties]
      macos = ''
      arch = '󰣇'
      ubuntu = ''
      rocky = ''
      fedora = ''
      redhat = ''
      debian = ''
      manjaro = '󱘊'
      alma = ''
      android = ''
      windows = ''
      linux = ''

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ''
    foreground = 'white'
    background = 'blue'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '  {{.Path}} '
    foreground = 'white'
    background = 'blue'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ''
    foreground = 'blue'
    background = 'black'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = ' {{ if .SSHSession }}󰣀 {{ end }}{{ .UserName }}@{{ .HostName }} '
    foreground = 'white'
    background = 'black'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ''
    foreground = 'black'
    background = 'white'

  [[blocks.segments]]
    type = "shell"
    style = "plain"
    foreground = "black"
    background = "white"

    [blocks.segments.properties.mapped_shell_names]
      pwsh = ''
      powershell = ''
      zsh = 'zsh'
      bash = ''

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ''
    foreground = 'white'
    background = 'transparent'

  [[blocks.segments]] # Das markierte Segment
    type = 'text'
    style = 'plain'
    template = '────────────────────────────────────────────────────' # Dynamische Füllung durch genügend Zeichen
    foreground = 'white'
    background = 'transparent'


[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ''
    foreground = 'white'
    background = 'transparent'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    template = ' at {{.CurrentDate | date .Format}}  '
    foreground = 'black'
    background = 'white'

    [blocks.segments.properties]
      time_format = '02/01/2006 | 15:04:05.000'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '─╮'
    foreground = 'white'
    background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '╰─'
    foreground = 'white'
    background = 'transparent'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = 'white'
    background = 'transparent'
    template = '$'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ' '
    foreground = 'white'
    background = 'transparent'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '─╯'
    foreground = 'white'
    background = 'transparent'

[transient_prompt]
background = 'transparent'
foreground = 'white'
template = '󰁔 '