[files]
rules = [
    { name = "*", is = "block", fg = "34" },  # Blau
    { name = "*", is = "char", fg = "32", bold = true },  # Grün
    { name = "*/", fg = "36" },  # Cyan
    { name = "*", is = "exec", fg = "33", bold = true },  # Gelb
    { name = "*", is = "fifo", fg = "35" },  # Magenta
    { name = "*", is = "orphan", fg = "30", bg = "41", bold = true },  # Rot
    { name = "*", is = "sock", fg = "35" },  # Magenta
    { name = "*", is = "sticky", fg = "36", bg = "16" },  # Dunkelgrau
    { name = "*LS_COLORS", fg = "35", bg = "40", bold = true, underline = true },  # Dunkelmagenta
    { name = "*.txt", fg = "7" },  # Standard
    { name = "*README", fg = "33", bold = true },  # Gelb
    { name = "*README.rst", fg = "33", bold = true },  # Gelb
    { name = "*README.md", fg = "33", bold = true },  # Gelb
    { name = "*LICENSE", fg = "33", bold = true },  # Gelb
    { name = "*LICENSE.md", fg = "33", bold = true },  # Gelb
    { name = "*COPYING", fg = "33", bold = true },  # Gelb
    { name = "*INSTALL", fg = "33", bold = true },  # Gelb
    { name = "*COPYRIGHT", fg = "33", bold = true },  # Gelb
    { name = "*AUTHORS", fg = "33", bold = true },  # Gelb
    { name = "*HISTORY", fg = "33", bold = true },  # Gelb
    { name = "*CONTRIBUTORS", fg = "33", bold = true },  # Gelb
    { name = "*CONTRIBUTING", fg = "33", bold = true },  # Gelb
    { name = "*CONTRIBUTING.md", fg = "33", bold = true },  # Gelb
    { name = "*CHANGELOG", fg = "33", bold = true },  # Gelb
    { name = "*CHANGELOG.md", fg = "33", bold = true },  # Gelb
    { name = "*CODEOWNERS", fg = "33", bold = true },  # Gelb
    { name = "*PATENTS", fg = "33", bold = true },  # Gelb
    { name = "*VERSION", fg = "33", bold = true },  # Gelb
    { name = "*NOTICE", fg = "33", bold = true },  # Gelb
    { name = "*CHANGES", fg = "33", bold = true },  # Gelb
    { name = "*.log", fg = "11" },  # Gelb
    { name = "*.adoc", fg = "11" },  # Gelb
    { name = "*.asciidoc", fg = "11" },  # Gelb
    { name = "*.etx", fg = "11" },  # Gelb
    { name = "*.info", fg = "11" },  # Gelb
    { name = "*.markdown", fg = "11" },  # Gelb
    { name = "*.md", fg = "11" },  # Gelb
    { name = "*.mkd", fg = "11" },  # Gelb
    { name = "*.mdx", fg = "11" },  # Gelb
    { name = "*.nfo", fg = "11" },  # Gelb
    { name = "*.org", fg = "11" },  # Gelb
    { name = "*.norg", fg = "11" },  # Gelb
    { name = "*.pod", fg = "11" },  # Gelb
    { name = "*.rst", fg = "11" },  # Gelb
    { name = "*.tex", fg = "11" },  # Gelb
    { name = "*.textile", fg = "11" },  # Gelb
    { name = "*.bib", fg = "11" },  # Gelb
    { name = "*.json", fg = "11" },  # Gelb
    { name = "*.jsonc", fg = "11" },  # Gelb
    { name = "*.json5", fg = "11" },  # Gelb
    { name = "*.hjson", fg = "11" },  # Gelb
    { name = "*.jsonl", fg = "11" },  # Gelb
    { name = "*.jsonnet", fg = "11" },  # Gelb
    { name = "*.libsonnet", fg = "11" },  # Gelb
    { name = "*.ndjson", fg = "11" },  # Gelb
    { name = "*.msg", fg = "11" },  # Gelb
    { name = "*.pgn", fg = "11" },  # Gelb
    { name = "*.rss", fg = "11" },  # Gelb
    { name = "*.xml", fg = "11" },  # Gelb
    { name = "*.fxml", fg = "11" },  # Gelb
    { name = "*.toml", fg = "11" },  # Gelb
    { name = "*.yaml", fg = "11" },  # Gelb
    { name = "*.yml", fg = "11" },  # Gelb
    { name = "*.RData", fg = "11" },  # Gelb
    { name = "*.rdata", fg = "11" },  # Gelb
    { name = "*.xsd", fg = "11" },  # Gelb
    { name = "*.dtd", fg = "11" },  # Gelb
    { name = "*.sgml", fg = "11" },  # Gelb
    { name = "*.rng", fg = "11" },  # Gelb
    { name = "*.rnc", fg = "11" },  # Gelb
    { name = "*.accdb", fg = "7" },  # Standard
    { name = "*.accde", fg = "7" },  # Standard
    { name = "*.accdr", fg = "7" },  # Standard
    { name = "*.accdt", fg = "7" },  # Standard
    { name = "*.db", fg = "7" },  # Standard
    { name = "*.fmp12", fg = "7" },  # Standard
    { name = "*.fp7", fg = "7" },  # Standard
    { name = "*.localstorage", fg = "7" },  # Standard
    { name = "*.mdb", fg = "7" },  # Standard
    { name = "*.mde", fg = "7" },  # Standard
    { name = "*.sqlite", fg = "7" },  # Standard
    { name = "*.typelib", fg = "7" },  # Standard
    { name = "*.nc", fg = "7" },  # Standard
    { name = "*.cbr", fg = "5" },  # Magenta
    { name = "*.cbz", fg = "5" },  # Magenta
    { name = "*.chm", fg = "5" },  # Magenta
    { name = "*.djvu", fg = "5" },  # Magenta
    { name = "*.pdf", fg = "5" },  # Magenta
    { name = "*.PDF", fg = "5" },  # Magenta
    { name = "*.mobi", fg = "5" },  # Magenta
    { name = "*.epub", fg = "5" },  # Magenta
    { name = "*.docm", fg = "12", underline = true },  # Blau
    { name = "*.doc", fg = "12" },  # Blau
    { name = "*.docx", fg = "12" },  # Blau
    { name = "*.odb", fg = "12" },  # Blau
    { name = "*.odt", fg = "12" },  # Blau
    { name = "*.rtf", fg = "12" },  # Blau
	{ name = "*.xls", fg = "12" },  # Blau
	{ name = "*.xlsx", fg = "12" },  # Blau
	{ name = "*.ppt", fg = "12" },  # Blau
	{ name = "*.pptx", fg = "12" },  # Blau
	{ name = "*.ods", fg = "12" },  # Blau
	{ name = "*.epub", fg = "12" },  # Blau
	{ name = "*.otf", fg = "12" },  # Blau
	{ name = "*.ttf", fg = "12" },  # Blau
	{ name = "*.woff", fg = "12" },  # Blau
	{ name = "*.woff2", fg = "12" },  # Blau
	{ name = "*.eot", fg = "12" },  # Blau
	{ name = "*.pfb", fg = "12" },  # Blau
	{ name = "*.pfm", fg = "12" },  # Blau
	{ name = "*.afm", fg = "12" },  # Blau
	{ name = "*.fnt", fg = "12" },  # Blau
	{ name = "*.fon", fg = "12" },  # Blau
	{ name = "*.ttc", fg = "12" },  # Blau
	{ name = "*.pfa", fg = "12" },  # Blau
	{ name = "*.log", fg = "12" },  # Blau
	{ name = "*.pl", fg = "12" },  # Blau
	{ name = "*.pm", fg = "12" },  # Blau
	{ name = "*.plx", fg = "12" },  # Blau
	{ name = "*.m", fg = "12" },  # Blau
	{ name = "*.mi", fg = "12" },  # Blau
	{ name = "*.am", fg = "12" },  # Blau
	{ name = "*.pmx", fg = "12" },  # Blau
	{ name = "*.pyd", fg = "12" },  # Blau
	{ name = "*.pyo", fg = "12" },  # Blau
	{ name = "*.pyc", fg = "12" },  # Blau
	{ name = "*.pkl", fg = "12" },  # Blau
	{ name = "*.pklz", fg = "12" },  # Blau
	{ name = "*.sqlite3", fg = "12" },  # Blau
	{ name = "*.s3db", fg = "12" },  # Blau
	{ name = "*.sdb", fg = "12" },  # Blau
	{ name = "*.db3", fg = "12" },  # Blau
	{ name = "*.dylib", fg = "12" },  # Blau
	{ name = "*.so", fg = "12" },  # Blau
	{ name = "*.bin", fg = "12" },  # Blau
	{ name = "*.out", fg = "12" },  # Blau
	{ name = "*.tar", fg = "12" },  # Blau
	{ name = "*.gz", fg = "12" },  # Blau
	{ name = "*.bz2", fg = "12" },  # Blau
	{ name = "*.xz", fg = "12" },  # Blau
	{ name = "*.7z", fg = "12" },  # Blau
	{ name = "*.zip", fg = "12" },  # Blau
	{ name = "*.rar", fg = "12" },  # Blau
	{ name = "*.tar.gz", fg = "12" },  # Blau
	{ name = "*.tar.bz2", fg = "12" },  # Blau
	{ name = "*.tar.xz", fg = "12" },  # Blau
	{ name = "*.tgz", fg = "12" },  # Blau
	{ name = "*.tbz", fg = "12" },  # Blau
	{ name = "*.txz", fg = "12" },  # Blau
	{ name = "*.tar.lz", fg = "12" },  # Blau
	{ name = "*.tar.lzma", fg = "12" },  # Blau
	{ name = "*.tar.zst", fg = "12" },  # Blau
	{ name = "*.rar", fg = "12" },  # Blau
	{ name = "*.zst", fg = "12" },  # Blau
	{ name = "*.iso", fg = "12" },  # Blau
	{ name = "*.nzb", fg = "12" },  # Blau
	{ name = "*.cpl", fg = "12" },  # Blau
	{ name = "*.so", fg = "12" },  # Blau
	{ name = "*.lib", fg = "12" },  # Blau
	{ name = "*.la", fg = "12" },  # Blau
	{ name = "*.lbi", fg = "12" },  # Blau
	{ name = "*.mlo", fg = "12" },  # Blau
	{ name = "*.a", fg = "12" },  # Blau
	{ name = "*.p", fg = "12" },  # Blau
	{ name = "*.b", fg = "12" },  # Blau
	{ name = "*.o", fg = "12" },  # Blau
	{ name = "*.po", fg = "12" },  # Blau
	{ name = "*.mo", fg = "12" },  # Blau
	{ name = "*.bpo", fg = "12" },  # Blau
	{ name = "*.mo", fg = "12" },  # Blau
	{ name = "*.py", fg = "12" },  # Blau
	{ name = "*.scala", fg = "12" },  # Blau
	{ name = "*.clj", fg = "12" },  # Blau
	{ name = "*.el", fg = "12" },  # Blau
	{ name = "*.pl", fg = "12" },  # Blau
	{ name = "*.ex", fg = "12" },  # Blau
	{ name = "*.exs", fg = "12" },  # Blau
	{ name = "*.erl", fg = "12" },  # Blau
	{ name = "*.hrl", fg = "12" },  # Blau
	{ name = "*.js", fg = "12" },  # Blau
	{ name = "*.ts", fg = "12" },  # Blau
	{ name = "*.c", fg = "12" },  # Blau
	{ name = "*.cpp", fg = "12" },  # Blau
	{ name = "*.cxx", fg = "12" },  # Blau
	{ name = "*.h", fg = "12" },  # Blau
	{ name = "*.hpp", fg = "12" },  # Blau
	{ name = "*.cc", fg = "12" },  # Blau
	{ name = "*.java", fg = "12" },  # Blau
	{ name = "*.rb", fg = "12" },  # Blau
	{ name = "*.php", fg = "12" },  # Blau
	{ name = "*.sql", fg = "12" },  # Blau
	{ name = "*.pl", fg = "12" },  # Blau
	{ name = "*.pm", fg = "12" },  # Blau
	{ name = "*.go", fg = "12" },  # Blau
	{ name = "*.rs", fg = "12" },  # Blau
	{ name = "*.lua", fg = "12" },  # Blau
	{ name = "*.sh", fg = "12" },  # Blau
	{ name = "*.bat", fg = "12" },  # Blau
	{ name = "*.cmd", fg = "12" },  # Blau
	{ name = "*.ps1", fg = "12" },  # Blau
	{ name = "*.psm1", fg = "12" },  # Blau
	{ name = "*.json", fg = "12" },  # Blau
	{ name = "*.yml", fg = "12" },  # Blau
	{ name = "*.yaml", fg = "12" },  # Blau
	{ name = "*.ini", fg = "12" },  # Blau
	{ name = "*.conf", fg = "12" },  # Blau
	{ name = "*.conf.d", fg = "12" },  # Blau
	{ name = "*.conf.d/", fg = "12" },  # Blau
]